# -*- coding: utf-8 -*-
"""
Project Euler Problems
----------------------
Highly divisible triangular number :

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

Solution is : 76576500 has 576 divider

"""
from math import *

i = 1
somme = 0
div_cnt = 0

def div_counter(value):
    cnt = 0
    max_val = floor(sqrt(value))
    
    for i in range(1 , max_val + 1):
        if (value % i) == 0:
            cnt = cnt + 1
    return cnt*2

while i > 0 :
    somme = somme + i
    i = i + 1
    div_cnt = div_counter(somme)
    if div_cnt > 500:
        break

print(somme,"has",div_cnt,"divider")
        
    
    
    
"""
for i in range(1,90000):
    somme = somme + i
    vect.append(somme)
    vect_len = len(vect)
    for j in range(vect_len):
        div_cnt = div_counter(vect[j])
        if div_cnt > div_cnt_prev :
            div_cnt_prev = div_cnt
"""           
  
        


 # print(vect[j],"has",,"divisors")





























